id: I9869BB86
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T15:06:39+00:00'
last_modified: '2022-06-07T15:06:32.951810+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ57648
  title: འབྲུག་ལུགས་ཀྱི་ཕྱག་ཆེན་ཁྲིད་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    51A1:
      image_group_id: I4CZ57655
      title: ''
      total_pages: 688
      order: 1
      base_file: 51A1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
