id: I9869BB86
legacy_id: P001775
ocr_import_info:
  bdrc_scan_id: W4CZ57648
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T15:01:57'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T20:37:28.440214+00:00'
last_modified: 2022-09-04 04:37:46.124379
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ57648
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ57648
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འབྲུག་ལུགས་ཀྱི་ཕྱག་ཆེན་ཁྲིད་སྐོར།
  author: འབྲུག་རྗེ་མཁན་པོ ༦༨་བསྟན་འཛིན་དོན་ཀུན་སྒྲུབ་པའི་སྡེ།
statistics:
  ocr_word_mean_confidence_index: 0.6222425223470942
  ocr_word_median_confidence_index: 0.6499999761581421
quality: null
bases:
  I4CZ57655:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ57655
      total_pages: 688
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CZ57655.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6222425223470942
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
