id: P001775
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 10:20:50.424575
source_metadata:
  id: bdr:W4CZ57648
  title: འབྲུག་ལུགས་ཀྱི་ཕྱག་ཆེན་ཁྲིད་སྐོར།
  author: ''
  volumes:
    c8229df0fe214ab2a20579ce085f05fa:
      image_group_id: I4CZ57655
      title: ''
      volume_number: 1
      total_pages: 688
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
